// <auto-generated />
using System;
using Gorodki.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gorodki.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923105804_RunReadiness")]
    partial class RunReadiness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("area_square_meters");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EndSeq")
                        .HasColumnType("integer")
                        .HasColumnName("end_seq");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<short?>("RejectReason")
                        .HasColumnType("smallint")
                        .HasColumnName("reject_reason");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Geometry>("Shape")
                        .HasColumnType("geometry(Geometry, 32634)")
                        .HasColumnName("shape");

                    b.Property<int>("StartSeq")
                        .HasColumnType("integer")
                        .HasColumnName("start_seq");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_captures");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_captures_run_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_captures_user_id_created_at");

                    b.ToTable("captures", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.GameConfigEntity", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.HasKey("Version")
                        .HasName("pk_game_configs");

                    b.ToTable("game_configs", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.InviteEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Code")
                        .HasName("pk_invites");

                    b.ToTable("invites", "app", t =>
                        {
                            t.HasCheckConstraint("ck_invites_uses", "used_count >= 0 AND used_count <= max_uses");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.ParcelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 32634)")
                        .HasColumnName("geometry");

                    b.Property<DateTimeOffset>("LastLevelUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_level_up_at");

                    b.Property<DateTimeOffset>("LastVisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("ShieldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shield_until");

                    b.Property<DateTimeOffset?>("SiegeUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("siege_until");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_parcels_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_parcels_owner_id");

                    b.HasIndex("League", "TileX", "TileY")
                        .HasDatabaseName("ix_parcels_league_tile_x_tile_y");

                    b.ToTable("parcels", "app", t =>
                        {
                            t.HasCheckConstraint("ck_parcels_geometry_valid", "extensions.st_isvalid(geometry)");

                            t.HasCheckConstraint("ck_parcels_level", "level BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunChunkEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("FirstSeq")
                        .HasColumnType("integer")
                        .HasColumnName("first_seq");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<long>("FirstPointMs")
                        .HasColumnType("bigint")
                        .HasColumnName("first_point_ms");

                    b.Property<long>("LastPointMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_point_ms");

                    b.Property<int>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.Property<byte[]>("Points")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("points");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("SensorsCompleteThroughMs")
                        .HasColumnType("bigint")
                        .HasColumnName("sensors_complete_through_ms");

                    b.HasKey("RunId", "FirstSeq")
                        .HasName("pk_run_chunks");

                    b.HasIndex("RunId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_run_chunks_run_id_content_hash");

                    b.ToTable("run_chunks", "app", t =>
                        {
                            t.HasCheckConstraint("ck_run_chunks_seq", "first_seq >= 0 AND last_seq >= first_seq");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<long>("ClockSkewMs")
                        .HasColumnType("bigint")
                        .HasColumnName("clock_skew_ms");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("config_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int?>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<bool>("MotionAuthorized")
                        .HasColumnType("boolean")
                        .HasColumnName("motion_authorized");

                    b.Property<bool>("Newcomer")
                        .HasColumnType("boolean")
                        .HasColumnName("newcomer");

                    b.Property<int>("PrefixEndSeq")
                        .HasColumnType("integer")
                        .HasColumnName("prefix_end_seq");

                    b.Property<long>("PrefixSensorsMs")
                        .HasColumnType("bigint")
                        .HasColumnName("prefix_sensors_ms");

                    b.Property<int>("ProcessedSeq")
                        .HasColumnType("integer")
                        .HasColumnName("processed_seq");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("StoredBytes")
                        .HasColumnType("integer")
                        .HasColumnName("stored_bytes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("ConfigVersion")
                        .HasDatabaseName("ix_runs_config_version");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_runs_one_active_per_user")
                        .HasFilter("status = 0");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_runs_user_id_started_at");

                    b.ToTable("runs", "app", t =>
                        {
                            t.HasCheckConstraint("ck_runs_counters", "chunk_count >= 0 AND stored_bytes >= 0");

                            t.HasCheckConstraint("ck_runs_last_seq", "last_seq IS NULL OR last_seq >= -1");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.TileVersionEntity", b =>
                {
                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("League", "TileX", "TileY")
                        .HasName("pk_tile_versions");

                    b.ToTable("tile_versions", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AgeConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("age_confirmed_at");

                    b.Property<string>("AppleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apple_subject");

                    b.Property<short>("ColorIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("color_index");

                    b.Property<int?>("ConsentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("consent_version");

                    b.Property<DateTimeOffset?>("ConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consented_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("display_name");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invite_code");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("normalized_name");

                    b.Property<bool>("PublicProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("public_profile");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AppleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_apple_subject")
                        .HasFilter("apple_subject IS NOT NULL");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject")
                        .HasFilter("google_subject IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_name");

                    b.ToTable("users", "app", t =>
                        {
                            t.HasCheckConstraint("ck_users_color_index", "color_index BETWEEN 0 AND 11");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_captures_runs_run_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.ParcelEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcels_users_owner_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RefreshTokenEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunChunkEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_chunks_runs_run_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.GameConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runs_game_configs_config_version");

                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
