// <auto-generated />
using System;
using Gorodki.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gorodki.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924092755_WorkerRetries")]
    partial class WorkerRetries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("capture_apply_seq");

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<long?>("AppliedSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_seq");

                    b.Property<string>("AreaByOutcome")
                        .HasColumnType("jsonb")
                        .HasColumnName("area_by_outcome");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("area_square_meters");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ChangedTiles")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_tiles");

                    b.Property<int>("ClaimNo")
                        .HasColumnType("integer")
                        .HasColumnName("claim_no");

                    b.Property<short>("Closure")
                        .HasColumnType("smallint")
                        .HasColumnName("closure");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<int>("EndSeq")
                        .HasColumnType("integer")
                        .HasColumnName("end_seq");

                    b.Property<double>("EstimatedArea")
                        .HasColumnType("double precision")
                        .HasColumnName("estimated_area");

                    b.Property<DateTimeOffset?>("EvidenceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RejectCode")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("reject_code");

                    b.Property<Guid?>("RollbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollback_id");

                    b.Property<double?>("RolledBackArea")
                        .HasColumnType("double precision")
                        .HasColumnName("rolled_back_area");

                    b.Property<DateTimeOffset?>("RolledBackAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rolled_back_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Geometry>("Shape")
                        .HasColumnType("geometry(Geometry, 32634)")
                        .HasColumnName("shape");

                    b.Property<int>("StartSeq")
                        .HasColumnType("integer")
                        .HasColumnName("start_seq");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int?>("TerritoryConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("territory_config_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_captures");

                    b.HasIndex("RunId", "ClaimNo")
                        .IsUnique()
                        .HasDatabaseName("ix_captures_run_id_claim_no");

                    b.HasIndex("Status", "LeaseUntil")
                        .HasDatabaseName("ix_captures_status_lease_until")
                        .HasFilter("status = 0");

                    b.HasIndex("UserId", "EffectiveAt")
                        .HasDatabaseName("ix_captures_user_id_effective_at")
                        .HasFilter("status = 1");

                    b.ToTable("captures", "app", t =>
                        {
                            t.HasCheckConstraint("ck_captures_seq", "start_seq >= 0 AND end_seq > start_seq");

                            t.HasCheckConstraint("ck_captures_status", "status BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureJournalEntity", b =>
                {
                    b.Property<Guid>("CaptureId")
                        .HasColumnType("uuid")
                        .HasColumnName("capture_id");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<byte[]>("Footprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("footprint");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.HasKey("CaptureId", "TileX", "TileY")
                        .HasName("pk_capture_journal");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("ix_capture_journal_applied_at");

                    b.ToTable("capture_journal", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureJournalPieceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("After")
                        .HasColumnType("boolean")
                        .HasColumnName("after");

                    b.Property<Guid>("CaptureId")
                        .HasColumnType("uuid")
                        .HasColumnName("capture_id");

                    b.Property<byte[]>("Geometry")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("geometry");

                    b.Property<DateTimeOffset>("LastLevelUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_level_up_at");

                    b.Property<DateTimeOffset>("LastVisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.PrimitiveCollection<Guid[]>("LossAttackers")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("loss_attackers");

                    b.Property<DateTimeOffset?>("LossWindowSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loss_window_since");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("ShieldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shield_until");

                    b.Property<DateTimeOffset?>("SiegeUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("siege_until");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.HasKey("Id")
                        .HasName("pk_capture_journal_pieces");

                    b.HasIndex("CaptureId", "TileX", "TileY")
                        .HasDatabaseName("ix_capture_journal_pieces_capture_id_tile_x_tile_y");

                    b.ToTable("capture_journal_pieces", "app", t =>
                        {
                            t.HasCheckConstraint("ck_capture_journal_pieces_level", "level BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureRollbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<double>("RestoredArea")
                        .HasColumnType("double precision")
                        .HasColumnName("restored_area");

                    b.Property<int>("RolledBack")
                        .HasColumnType("integer")
                        .HasColumnName("rolled_back");

                    b.Property<double>("SkippedArea")
                        .HasColumnType("double precision")
                        .HasColumnName("skipped_area");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WithoutJournal")
                        .HasColumnType("integer")
                        .HasColumnName("without_journal");

                    b.HasKey("Id")
                        .HasName("pk_capture_rollbacks");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_capture_rollbacks_requested_at")
                        .HasFilter("status = 0");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_capture_rollbacks_user_id");

                    b.ToTable("capture_rollbacks", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.FogTileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Layer")
                        .HasColumnType("smallint")
                        .HasColumnName("layer");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.Property<byte[]>("Bits")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bits");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer")
                        .HasColumnName("cell_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId", "Layer", "Season", "TileX", "TileY")
                        .HasName("pk_fog_tiles");

                    b.ToTable("fog_tiles", "app", t =>
                        {
                            t.HasCheckConstraint("ck_fog_tiles_cells", "cell_count BETWEEN 1 AND 65536");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.GameConfigEntity", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.HasKey("Version")
                        .HasName("pk_game_configs");

                    b.ToTable("game_configs", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.InviteEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Code")
                        .HasName("pk_invites");

                    b.ToTable("invites", "app", t =>
                        {
                            t.HasCheckConstraint("ck_invites_uses", "used_count >= 0 AND used_count <= max_uses");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.LeaderboardSnapshotEntity", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<short>("Board")
                        .HasColumnType("smallint")
                        .HasColumnName("board");

                    b.Property<short>("Layer")
                        .HasColumnType("smallint")
                        .HasColumnName("layer");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Day", "Board", "Layer", "Season", "UserId")
                        .HasName("pk_leaderboard_snapshots");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_leaderboard_snapshots_user_id");

                    b.HasIndex("Day", "Board", "Layer", "Season", "Rank")
                        .HasDatabaseName("ix_leaderboard_snapshots_day_board_layer_season_rank");

                    b.ToTable("leaderboard_snapshots", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.ParcelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 32634)")
                        .HasColumnName("geometry");

                    b.Property<DateTimeOffset>("LastLevelUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_level_up_at");

                    b.Property<DateTimeOffset>("LastVisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.PrimitiveCollection<Guid[]>("LossAttackers")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("loss_attackers");

                    b.Property<DateTimeOffset?>("LossWindowSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loss_window_since");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("ShieldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shield_until");

                    b.Property<DateTimeOffset?>("SiegeUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("siege_until");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_parcels_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_parcels_owner_id");

                    b.HasIndex("League", "TileX", "TileY")
                        .HasDatabaseName("ix_parcels_league_tile_x_tile_y");

                    b.ToTable("parcels", "app", t =>
                        {
                            t.HasCheckConstraint("ck_parcels_geometry_valid", "extensions.st_isvalid(geometry)");

                            t.HasCheckConstraint("ck_parcels_level", "level BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.PrivacyZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_privacy_zones");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_privacy_zones_user_id");

                    b.ToTable("privacy_zones", "app", t =>
                        {
                            t.HasCheckConstraint("ck_privacy_zones_coordinates", "latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunChunkEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("FirstSeq")
                        .HasColumnType("integer")
                        .HasColumnName("first_seq");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<long>("FirstPointMs")
                        .HasColumnType("bigint")
                        .HasColumnName("first_point_ms");

                    b.Property<long>("LastPointMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_point_ms");

                    b.Property<int>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.Property<byte[]>("Points")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("points");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("SensorsCompleteThroughMs")
                        .HasColumnType("bigint")
                        .HasColumnName("sensors_complete_through_ms");

                    b.HasKey("RunId", "FirstSeq")
                        .HasName("pk_run_chunks");

                    b.HasIndex("RunId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_run_chunks_run_id_content_hash");

                    b.ToTable("run_chunks", "app", t =>
                        {
                            t.HasCheckConstraint("ck_run_chunks_seq", "first_seq >= 0 AND last_seq >= first_seq");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AcceptedMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accepted_meters");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<long>("ClockSkewMs")
                        .HasColumnType("bigint")
                        .HasColumnName("clock_skew_ms");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("config_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("FogFailures")
                        .HasColumnType("integer")
                        .HasColumnName("fog_failures");

                    b.Property<int?>("FogNewCells")
                        .HasColumnType("integer")
                        .HasColumnName("fog_new_cells");

                    b.Property<DateTimeOffset?>("FogRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fog_retry_at");

                    b.Property<DateTimeOffset?>("FogStampedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fog_stamped_at");

                    b.Property<int?>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<bool>("MotionAuthorized")
                        .HasColumnType("boolean")
                        .HasColumnName("motion_authorized");

                    b.Property<bool>("Newcomer")
                        .HasColumnType("boolean")
                        .HasColumnName("newcomer");

                    b.Property<DateTimeOffset?>("PointsPurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("points_purged_at");

                    b.Property<int>("PrefixEndSeq")
                        .HasColumnType("integer")
                        .HasColumnName("prefix_end_seq");

                    b.Property<long>("PrefixSensorsMs")
                        .HasColumnType("bigint")
                        .HasColumnName("prefix_sensors_ms");

                    b.Property<int>("ProcessedSeq")
                        .HasColumnType("integer")
                        .HasColumnName("processed_seq");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("StoredBytes")
                        .HasColumnType("integer")
                        .HasColumnName("stored_bytes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("VisitedParcels")
                        .HasColumnType("integer")
                        .HasColumnName("visited_parcels");

                    b.Property<int>("VisitsFailures")
                        .HasColumnType("integer")
                        .HasColumnName("visits_failures");

                    b.Property<DateTimeOffset?>("VisitsProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visits_processed_at");

                    b.Property<DateTimeOffset?>("VisitsRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visits_retry_at");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("ConfigVersion")
                        .HasDatabaseName("ix_runs_config_version");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_runs_device_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_runs_one_active_per_user")
                        .HasFilter("status = 0");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_runs_user_id_started_at");

                    b.ToTable("runs", "app", t =>
                        {
                            t.HasCheckConstraint("ck_runs_counters", "chunk_count >= 0 AND stored_bytes >= 0");

                            t.HasCheckConstraint("ck_runs_last_seq", "last_seq IS NULL OR last_seq >= -1");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.SeasonEntity", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Number")
                        .HasName("pk_seasons");

                    b.ToTable("seasons", "app", t =>
                        {
                            t.HasCheckConstraint("ck_seasons_minsk_midnight", "(starts_at AT TIME ZONE 'Europe/Minsk')::time = '00:00'");

                            t.HasCheckConstraint("ck_seasons_number", "number >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Number = 0,
                            Name = "Сезон 0 (бета)",
                            StartsAt = new DateTimeOffset(new DateTime(2026, 11, 15, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Number = 1,
                            Name = "Сезон 1",
                            StartsAt = new DateTimeOffset(new DateTime(2026, 11, 29, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Number = 2,
                            Name = "Сезон 2",
                            StartsAt = new DateTimeOffset(new DateTime(2026, 12, 13, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.TileVersionEntity", b =>
                {
                    b.Property<short>("League")
                        .HasColumnType("smallint")
                        .HasColumnName("league");

                    b.Property<int>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("League", "TileX", "TileY")
                        .HasName("pk_tile_versions");

                    b.ToTable("tile_versions", "app");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AgeConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("age_confirmed_at");

                    b.Property<string>("AppleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apple_subject");

                    b.Property<short>("ColorIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("color_index");

                    b.Property<int?>("ConsentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("consent_version");

                    b.Property<DateTimeOffset?>("ConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consented_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("FrozenUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_until");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invite_code");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("normalized_name");

                    b.Property<bool>("PublicProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("public_profile");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AppleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_apple_subject")
                        .HasFilter("apple_subject IS NOT NULL");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject")
                        .HasFilter("google_subject IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_name");

                    b.ToTable("users", "app", t =>
                        {
                            t.HasCheckConstraint("ck_users_color_index", "color_index BETWEEN 0 AND 11");
                        });
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_captures_runs_run_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureJournalEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.CaptureEntity", null)
                        .WithMany()
                        .HasForeignKey("CaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capture_journal_captures_capture_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureJournalPieceEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.CaptureJournalEntity", null)
                        .WithMany()
                        .HasForeignKey("CaptureId", "TileX", "TileY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capture_journal_pieces_capture_journal_capture_id_tile_x_ti");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.CaptureRollbackEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capture_rollbacks_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.FogTileEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fog_tiles_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.LeaderboardSnapshotEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_snapshots_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.ParcelEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcels_users_owner_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.PrivacyZoneEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_zones_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RefreshTokenEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunChunkEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_chunks_runs_run_id");
                });

            modelBuilder.Entity("Gorodki.Api.Infrastructure.Persistence.RunEntity", b =>
                {
                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.GameConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runs_game_configs_config_version");

                    b.HasOne("Gorodki.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
